package spotify.simulation.forms;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Genere;
import spotify.simulation.controller.GenereController;
import spotify.simulation.controller.SongController;
import spotify.simulation.utilidades.ImagePanel;

public class ManageGeneros extends javax.swing.JInternalFrame {

    private GenereController genereController;
    private List<Genere> listGenere;
    private Genere objGenere;
    private SongController songController;

    public ManageGeneros() {
        initComponents();

        //*****************************
        // Quitar bordes (incluso los invisibles o decorativos del LookAndFeel)
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));

        //****************
        // Diseño
        panelGenere.setBackground(new java.awt.Color(0, 66, 123, 200));
        panelGenere.setBorderColor(Color.WHITE);
        panelGenere.setBorderThickness(3);
        panelGenere.setRoundTopLeft(50);
        panelGenere.setRoundTopRight(50);
        panelGenere.setRoundBottomRight(50);
        panelGenere.setRoundBottomLeft(50);

        if (panelLogo4 instanceof ImagePanel) {
            ((ImagePanel) panelLogo4).setImage("/spotify/simulation/imagenes/logo.png");
        }

        //******************
        // Logica
        genereController = new GenereController();
        songController = new SongController();
        listGenere = new ArrayList<>();
        objGenere = new Genere();
        this.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelGenere = new spotify.simulation.utilidades.PanelRound();
        round5 = new spotify.simulation.utilidades.Round();
        panelLogo4 = new spotify.simulation.utilidades.ImagePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalida = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        round7 = new spotify.simulation.utilidades.Round();
        txtNombreGenero = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        round8 = new spotify.simulation.utilidades.Round();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGenere.setBackground(new java.awt.Color(0, 102, 102));

        round5.setBackground(new java.awt.Color(255, 255, 255));
        round5.setRoundBottomLeft(100);
        round5.setRoundBottomRight(100);
        round5.setRoundTopLeft(100);
        round5.setRoundTopRight(100);

        javax.swing.GroupLayout panelLogo4Layout = new javax.swing.GroupLayout(panelLogo4);
        panelLogo4.setLayout(panelLogo4Layout);
        panelLogo4Layout.setHorizontalGroup(
            panelLogo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        panelLogo4Layout.setVerticalGroup(
            panelLogo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout round5Layout = new javax.swing.GroupLayout(round5);
        round5.setLayout(round5Layout);
        round5Layout.setHorizontalGroup(
            round5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(round5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(round5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelLogo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        round5Layout.setVerticalGroup(
            round5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(round5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(round5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelLogo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSalida);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENEROS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRAR");

        jPanel1.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");

        round7.setBackground(new java.awt.Color(255, 255, 255));
        round7.setForeground(new java.awt.Color(255, 255, 255));
        round7.setRoundBottomLeft(30);
        round7.setRoundBottomRight(30);
        round7.setRoundTopLeft(30);
        round7.setRoundTopRight(30);

        txtNombreGenero.setBorder(null);

        javax.swing.GroupLayout round7Layout = new javax.swing.GroupLayout(round7);
        round7.setLayout(round7Layout);
        round7Layout.setHorizontalGroup(
            round7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        round7Layout.setVerticalGroup(
            round7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombreGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        round8.setBackground(new java.awt.Color(255, 255, 255));
        round8.setForeground(new java.awt.Color(255, 255, 255));
        round8.setRoundBottomLeft(30);
        round8.setRoundBottomRight(30);
        round8.setRoundTopLeft(30);
        round8.setRoundTopRight(30);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        txtDescripcion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtDescripcion);

        javax.swing.GroupLayout round8Layout = new javax.swing.GroupLayout(round8);
        round8.setLayout(round8Layout);
        round8Layout.setHorizontalGroup(
            round8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        round8Layout.setVerticalGroup(
            round8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnActualizar.setBackground(new java.awt.Color(0, 66, 123));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(246, 206, 1));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(222, 36, 24));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESCRIPCIÓN");

        javax.swing.GroupLayout panelGenereLayout = new javax.swing.GroupLayout(panelGenere);
        panelGenere.setLayout(panelGenereLayout);
        panelGenereLayout.setHorizontalGroup(
            panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGenereLayout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGenereLayout.createSequentialGroup()
                        .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(round8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGenereLayout.createSequentialGroup()
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(round7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGenereLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGenereLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(78, 78, 78))))
            .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGenereLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGenereLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelGenereLayout.createSequentialGroup()
                            .addComponent(round5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelGenereLayout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(jLabel1))
                                .addGroup(panelGenereLayout.createSequentialGroup()
                                    .addGap(139, 139, 139)
                                    .addComponent(jLabel2)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 191, Short.MAX_VALUE)
                    .addComponent(btnCerrar)
                    .addGap(20, 20, 20)))
        );
        panelGenereLayout.setVerticalGroup(
            panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGenereLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(round7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(round8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGenereLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGenereLayout.createSequentialGroup()
                            .addGroup(panelGenereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(round5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelGenereLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addGroup(panelGenereLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(btnCerrar)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        getContentPane().add(panelGenere, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaSalida.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(panelGenere, "Por favor, seleccione un género de la tabla.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        objGenere = listGenere.get(filaSeleccionada);

        if (filaSeleccionada >= 0 && filaSeleccionada < listGenere.size()) {
            int confirmacion = JOptionPane.showConfirmDialog(
                    null,
                    "¿Está seguro de que desea eliminar este género?",
                    "Confirmación de eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                if (!songController.hasAssociatedSongs(objGenere.getIdGenere())) {
                    genereController.deleteGenere(objGenere.getIdGenere());
                    JOptionPane.showMessageDialog(panelGenere, "El género se eliminó exitosamente.", "Eliminación completada", JOptionPane.INFORMATION_MESSAGE);
                    this.llenarTabla();
                    txtDescripcion.setText("");
                    txtNombreGenero.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede eliminar el género porque está asociado a una o más canciones.", "Acción no permitida", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El proceso de eliminación fue cancelado.", "Operación cancelada", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panelGenere, "El índice seleccionado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int filaSeleccionada = tablaSalida.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(panelGenere, "Debe seleccionar un género de la tabla.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        objGenere = listGenere.get(filaSeleccionada);
        String nombreGenero = txtNombreGenero.getText();
        String detalleGenero = txtDescripcion.getText();

        if (nombreGenero != null && detalleGenero != null) {
            if (!nombreGenero.trim().isEmpty() && !detalleGenero.trim().isEmpty()) {
                genereController.updateGenere(objGenere.getIdGenere(), nombreGenero, detalleGenero);
                JOptionPane.showMessageDialog(panelGenere, "La información del género ha sido actualizada exitosamente.", "Actualización completada", JOptionPane.INFORMATION_MESSAGE);
                this.llenarTabla();
                txtDescripcion.setText("");
                txtNombreGenero.setText("");
            } else {
                JOptionPane.showMessageDialog(panelGenere, "Por favor, complete todos los campos antes de continuar.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panelGenere, "Los campos de entrada no pueden ser nulos.", "Error de datos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidaMouseClicked
        int index = tablaSalida.getSelectedRow();

        objGenere = listGenere.get(index);

        txtNombreGenero.setText(objGenere.getGenereName());
        txtDescripcion.setText(objGenere.getDescription());
    }//GEN-LAST:event_tablaSalidaMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombreGenero = txtNombreGenero.getText();
        String detalleGenero = txtDescripcion.getText();

        if (nombreGenero != null && detalleGenero != null) {
            if (!nombreGenero.trim().isEmpty() && !detalleGenero.trim().isEmpty()) {
                genereController.addGenere(nombreGenero, detalleGenero);
                JOptionPane.showMessageDialog(panelGenere, "El género se ha registrado con éxito.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                this.llenarTabla();
                txtDescripcion.setText("");
                txtNombreGenero.setText("");
            } else {
                JOptionPane.showMessageDialog(panelGenere, "Todos los campos deben ser completados.", "Campo vacío", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panelGenere, "No se permiten campos nulos. Verifique la información ingresada.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void llenarTabla() {

        listGenere = genereController.getAllGeneres();

        String[] textos = {"GENERO", "DESCRIPCIÓN"};
        DefaultTableModel modelTable = new DefaultTableModel(textos, 0);

        modelTable.setRowCount(0);

        for (Genere genere : listGenere) {
            Object[] objFila = new Object[2];

            objFila[0] = genere.getGenereName();
            objFila[1] = genere.getDescription();

            modelTable.addRow(objFila);
        }
        tablaSalida.setModel(modelTable);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private spotify.simulation.utilidades.PanelRound panelGenere;
    private spotify.simulation.utilidades.ImagePanel panelLogo4;
    private spotify.simulation.utilidades.Round round5;
    private spotify.simulation.utilidades.Round round7;
    private spotify.simulation.utilidades.Round round8;
    private javax.swing.JTable tablaSalida;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombreGenero;
    // End of variables declaration//GEN-END:variables
}
